name: Deploy to one.com

on:
  push:
    branches:
      - main

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show deployment info
        run: |
          echo "GitHub Actions werkt!"
          echo "Deploying commit:"
          git rev-parse --short HEAD